### ISSUE TITLE
BUG: navi does not support OpenApi operation `anyOf`

### ISSUE THREAD

**Issue by taxonomy-man** [lispyclouds/navi#9]
hi! 

Thanks for sharing this project, I have the same use case so Im trying it out right now! 👍 

I think I have found a bug, and It would be super nice to get it sorted out. I have case where it is possible to send in either a number or two string enums. From my understanding of openApi spec this is valid yaml. https://swagger.io/docs/specification/v3_0/data-models/oneof-anyof-allof-not/#oneof

```yaml
        - in: query
          name: version
          description: Taxonomy version, either number that indicates the version, "latest" for latest release, or "next" for unpublished changes (requires admin rights)
          schema:
            anyOf:
              - type: integer
                format: int64
              - type: string
                enum:
                  - latest
                  - next
```

but in my generated reitit routes the children (the schema options), and an exception is thrown if we try to start web server. 
  
```clojure
["/v1/taxonomy/main/concepts"
  {:get
   {:handler nil,
    :parameters
    {:query
     [:map
      [:offset {:optional true} #function[clojure.core/int?]]
      [:version {:optional true} [:or]]
      [:relation {:optional true} #function[clojure.core/string?--5494]]]},
```
      
 As you can see, the `:version` key here does just contain `[:or]`,
     so when I start web server I get this error 
```clojure    
       [{:type java.lang.RuntimeException,
    :message "could not start [#'dev/http-server] due to",
    :at [mount.core$up$fn__81798 invoke "core.cljc" 80]}
   {:type clojure.lang.ExceptionInfo,
    :message
    ":malli.core/child-error\n\n{:type :or, :properties nil, :children nil, :min 1, :max nil}",
    :data
    {:type :malli.core/child-error,
     :message :malli.core/child-error,
     :data
     {:type :or, :properties nil, :children nil, :min 1, :max nil},
     :reitit.exception/cause #error {
 :cause ":malli.core/child-error"
 :data {:type :malli.core/child-error, :message :malli.core/child-error, :data {:type :or, :properties nil, :children nil, :min 1, :max nil}}
 :via
 [{:type clojure.lang.ExceptionInfo
   :message ":malli.core/child-error"
   :data {:type :malli.core/child-error, :message :malli.core/child-error, :data {:type :or, :properties nil, :children nil, :min 1, :max nil}}
   :at [malli.core$_exception invokeStatic "core.cljc" 157]}]
```
